.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. spacexpanse_qt test_spacexpanse_qt
clean: FORCE
	$(MAKE) -C .. spacexpanse_qt_clean test_spacexpanse_qt_clean
check: FORCE
	$(MAKE) -C .. test_spacexpanse_qt_check
spacexpanse-qt spacexpanse-qt.exe: FORCE
	 $(MAKE) -C .. spacexpanse_qt
apk: FORCE
	$(MAKE) -C .. spacexpanse_qt_apk
